### ISSUE TITLE
Support tool names in addition to workflow names in execute command

### ISSUE THREAD

**Issue by mhmdiaa** [trickest/trickest-cli#20]
The CLI should start by searching the store for a `workflow` that matches the user's query. If nothing is found, it should search for a `tool` that matches the query and automatically create a new workflow with this tool only (and connect any parameters/inputs to it)

**Example**
`trickest execute amass --config config.yaml`
config.yaml
```
inputs:
  - amass.domain: example.com # should the `amass` prefix be added implicitly?
machines:
  - small: 0
  - medium: 0
  - large: 1
outputs:
  - amass # should this be optional?
```
